### PR TITLE
Fix Vendor Name from Oppo to OPPO

### PR DESCRIPTION
**Pull request by jumoog**

### CODE REVIEW

**Comment by maniac103** [comment]
What's wrong with 'Oppo'?

**Comment by jumoog** [comment]
OPPO told me that for Find7

**Comment by Rashed97** [comment]
This sting is purely aesthetic. We could name it "Samsung Galaxy S6" for all the system or anybof the blobs care. It's like your computers Bluetooth name.

**Comment by jumoog** [comment]
i know

**Pull request closed without merging**
